import { useEffect, useState } from 'react'
import api from './services/api'

const stages = [
  { key: 'discovery', label: 'Discover', path: 'discover', agent: 'Discovery Agent' },
  { key: 'positioning', label: 'Position', path: 'position', agent: 'Positioning Agent' },
  { key: 'shape', label: 'Shape', path: 'shape', agent: 'Brand Shaper' },
  { key: 'visualize', label: 'Visualize', path: 'visualize', agent: 'Visual Agent' },
  { key: 'challenge', label: 'Challenge', path: 'challenge', agent: 'Critic Agent' },
  { key: 'consistency', label: 'Consistency', path: 'consistency', agent: 'Consistency Agent' },
  { key: 'launch', label: 'Deliver', path: 'deliver', agent: 'Launch Agent' },
]
const stageFromPath = (path) => stages.find((stage) => path.endsWith(`/${stage.path}`))?.key || 'discovery'
const labelFor = (key) => stages.find((stage) => stage.key === key)?.label || 'Discover'
const prettyDate = (value) => value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'Recently'
const text = (value) => Array.isArray(value) ? value.map((item) => typeof item === 'object' ? item.name || item.segment || item.text || JSON.stringify(item) : item).join(', ') : value || 'Not yet defined'
const go = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }

function App() {
  const [path, setPath] = useState(window.location.pathname)
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('nexira_user') || 'null'))
  useEffect(() => { const handler = () => setPath(window.location.pathname); window.addEventListener('popstate', handler); return () => window.removeEventListener('popstate', handler) }, [])
  const signOut = () => { api.logout(); setUser(null); go('/') }
  const protectedPath = path.startsWith('/dashboard') || path.startsWith('/projects') || path.startsWith('/admin')
  if (protectedPath && !user) return <Auth mode="login" onAuth={(next) => { setUser(next); go('/dashboard') }} />
  if (path === '/login' || path === '/register') return <Auth mode={path.slice(1)} onAuth={(next) => { setUser(next); go(localStorage.getItem('nexira_pending_prompt') ? '/projects/new' : '/dashboard') }} />
  if (path === '/') return <Home user={user} />
  if (path === '/dashboard') return <Dashboard user={user} onSignOut={signOut} />
  if (path === '/projects/new') return <CreateProject onCreated={(project) => go(`/projects/${project.id}/discover`)} />
  if (path.startsWith('/admin')) return <Admin user={user} onSignOut={signOut} />
  if (path.startsWith('/projects/')) return <Workspace path={path} user={user} onSignOut={signOut} />
  return <Home user={user} />
}

function Header({ user }) { return <header className="public-header"><button className="wordmark" onClick={() => go('/')}>NEXIRA<span>.</span></button><nav>{user ? <button className="text-button" onClick={() => go('/dashboard')}>Workspace</button> : <><button className="text-button" onClick={() => go('/login')}>Log in</button><button className="button button-dark" onClick={() => go('/register')}>Start building â†—</button></>}</nav></header> }
function AppHeader({ user, project, onSignOut }) { return <header className="app-header"><button className="wordmark" onClick={() => go('/dashboard')}>NEXIRA<span>.</span></button>{project && <div className="project-crumb"><span>PROJECT</span><strong>{project.name}</strong></div>}<div className="header-actions"><span className="user-pill">{user?.first_name?.[0] || 'U'}</span><button className="text-button" onClick={onSignOut}>Sign out</button></div></header> }
function Shell({ children, user, project, onSignOut }) { return <div className="app-page"><AppHeader user={user} project={project} onSignOut={onSignOut} />{children}</div> }

function Home({ user }) {
  const [prompt, setPrompt] = useState('')
  const submit = () => { if (!prompt.trim()) return; localStorage.setItem('nexira_pending_prompt', prompt.trim()); go(user ? '/projects/new' : '/register') }
  return <div className="public-page"><Header user={user} /><main><section className="hero"><div><p className="kicker">BRAND INTELLIGENCE, WITH INTENT</p><h1>Turn an idea<br /><em>into a brand.</em></h1><p className="hero-lede">NEXIRA turns unfinished thoughts into a coherent brand system through a structured, human-led AI workflow.</p></div><div className="prompt-card"><div className="prompt-head"><span className="prompt-icon">âœ¦</span><span>New brand brief</span><span>{prompt.length}/4000</span></div><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Tell NEXIRA what you're building..." rows="5" /><div className="prompt-footer"><div className="chips">{['Startup', 'Product', 'Service', 'Brand'].map((chip) => <button key={chip} onClick={() => setPrompt((current) => current || `A ${chip.toLowerCase()} that `)}>{chip}</button>)}</div><button className="button button-accent" onClick={submit}>Start building â†—</button></div></div></section><section className="signal-row"><div><strong>7</strong><span>guided stages</span></div><div><strong>01</strong><span>human decision-maker</span></div><div><strong>âˆž</strong><span>ways to refine</span></div></section><section className="section-band"><div><p className="kicker">THE NEXIRA METHOD</p><h2>Strategy before<br /><em>surface.</em></h2></div><div className="stage-list">{stages.map((stage, index) => <div className="stage-row" key={stage.key}><span>0{index + 1}</span><strong>{stage.label.toUpperCase()}</strong><span>{['Understand the idea, audience, and problem.', 'Find the space your brand can own.', 'Give the brand a personality and voice.', 'Shape a visual world people recognize.', 'Pressure-test the choices before launch.', 'Check every relationship for coherence.', 'Package the system into launch-ready content.'][index]}</span></div>)}</div></section><section className="manifesto"><p className="kicker">A BETTER KIND OF AI WORKSPACE</p><h2>The machine brings range.<br /><em>You bring judgment.</em></h2><p>Every output stays visible, editable, and yours to approve. NEXIRA is built to make better decisions easier, not to make decisions for you.</p></section></main><footer className="public-footer"><span>NEXIRA.</span><span>Idea to identity, deliberately.</span></footer></div>
}

function Auth({ mode, onAuth }) { const register = mode === 'register'; const [form, setForm] = useState({ first_name: '', last_name: '', email: '', password: '', confirm: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const update = (key) => (value) => setForm({ ...form, [key]: value }); const submit = async (event) => { event.preventDefault(); setError(''); if (register && form.password !== form.confirm) return setError('Passwords do not match.'); setLoading(true); try { const result = await api.auth(register ? 'register' : 'login', register ? form : { email: form.email, password: form.password }); onAuth(result.user) } catch (err) { setError(err.message) } finally { setLoading(false) } }; return <div className="auth-page"><button className="wordmark" onClick={() => go('/')}>NEXIRA<span>.</span></button><div className="auth-wrap"><div className="auth-aside"><p className="kicker">THE BRAND WORKSPACE</p><h1>Make the<br /><em>meaning</em> visible.</h1><p>Move from raw concept to a brand you can stand behind, one considered decision at a time.</p></div><form className="auth-form" onSubmit={submit}><p className="kicker">{register ? 'CREATE YOUR ACCOUNT' : 'WELCOME BACK'}</p><h2>{register ? 'Start building.' : 'Continue building.'}</h2>{register && <div className="form-row"><Field label="First name" value={form.first_name} onChange={update('first_name')} /><Field label="Last name" value={form.last_name} onChange={update('last_name')} /></div>}<Field label="Email" type="email" value={form.email} onChange={update('email')} /><Field label="Password" type="password" value={form.password} onChange={update('password')} />{register && <Field label="Confirm password" type="password" value={form.confirm} onChange={update('confirm')} />}<button className="button button-dark full" disabled={loading}>{loading ? 'Connectingâ€¦' : register ? 'Create account â†—' : 'Log in â†—'}</button>{error && <p className="form-error">{error}</p>}<p className="switch-auth">{register ? 'Already have an account?' : 'New to NEXIRA?'} <button type="button" onClick={() => go(register ? '/login' : '/register')}>{register ? 'Log in' : 'Create one'}</button></p></form></div></div> }
function Field({ label, value, onChange, type = 'text' }) { return <label className="field"><span>{label}</span><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label> }

function Dashboard({ user, onSignOut }) { const [projects, setProjects] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { api.projects.list().then(setProjects).catch((err) => setError(err.message)).finally(() => setLoading(false)) }, []); const filtered = projects.filter((project) => project.name.toLowerCase().includes(query.toLowerCase())); return <Shell user={user} onSignOut={onSignOut}><main className="dashboard"><div className="page-heading"><div><p className="kicker">YOUR STUDIO</p><h1>Good work starts<br /><em>with a clear idea.</em></h1></div><button className="button button-accent" onClick={() => go('/projects/new')}>New project â†—</button></div><div className="dashboard-toolbar"><span>{projects.length} {projects.length === 1 ? 'project' : 'projects'}</span><input aria-label="Search projects" placeholder="Search projects" value={query} onChange={(event) => setQuery(event.target.value)} /></div>{error && <p className="form-error">{error}</p>}{loading ? <div className="empty-state">Loading your studioâ€¦</div> : filtered.length ? <div className="project-grid">{filtered.map((project) => <ProjectCard key={project.id} project={project} />)}</div> : <div className="empty-state"><span className="empty-mark">âœ¦</span><h3>{query ? 'No matches found' : 'Your studio is waiting.'}</h3><p>{query ? 'Try another search.' : 'Start with the idea that keeps returning.'}</p>{!query && <button className="button button-dark" onClick={() => go('/projects/new')}>Create your first project â†—</button>}</div>}</main></Shell> }
function ProjectCard({ project }) { const stage = stages.find((item) => item.key === project.current_stage); return <article className="project-card" onClick={() => go(`/projects/${project.id}/${stage?.path || 'discover'}`)}><div className="card-top"><span className={`status-dot ${project.status === 'completed' ? 'complete' : ''}`} />{project.status === 'completed' ? 'Brand ready' : 'In progress'}<span className="card-arrow">â†—</span></div><h3>{project.name}</h3><p>{project.initial_prompt}</p><div className="card-meta"><span>Current stage<br /><strong>{labelFor(project.current_stage)}</strong></span><span>Progress<br /><strong>{project.progress || 0}%</strong></span></div><div className="progress"><i style={{ width: `${project.progress || 0}%` }} /></div><small>Updated {prettyDate(project.updated_at)}</small></article> }

function CreateProject({ onCreated }) { const [name, setName] = useState(''); const [prompt, setPrompt] = useState(() => localStorage.getItem('nexira_pending_prompt') || ''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const project = await api.projects.create({ name, initial_prompt: prompt }); localStorage.removeItem('nexira_pending_prompt'); onCreated(project) } catch (err) { setError(err.message) } finally { setLoading(false) } }; return <Shell><main className="create-page"><button className="back-link" onClick={() => go('/dashboard')}>â† Back to studio</button><div className="create-intro"><div><p className="kicker">A NEW DIRECTION</p><h1>Create your<br /><em>brand.</em></h1></div><p>Give the idea a name and enough context for Discovery to begin its work.</p></div><form className="create-form" onSubmit={submit}><Field label="Project name" value={name} onChange={setName} /><label className="field"><span>Initial idea / prompt</span><textarea required rows="8" maxLength="4000" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="What are you building, who is it for, and why does it matter?" /></label><div className="form-bottom"><span>{prompt.length}/4000</span><button className="button button-accent" disabled={loading}>{loading ? 'Creatingâ€¦' : 'Start building â†—'}</button></div>{error && <p className="form-error">{error}</p>}</form></main></Shell> }

function Workspace({ path, user, onSignOut }) { const id = path.split('/')[2]; const active = stageFromPath(path); const [project, setProject] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); useEffect(() => { api.projects.get(id).then(setProject).catch((err) => setError(err.message)).finally(() => setLoading(false)) }, [id]); const act = async (action, stage = active, payload) => { setBusy(true); setError(''); try { setProject(await api.workflow.action(id, stage, action, payload)); setNotice(action === 'approve' ? `${labelFor(stage)} approved.` : `${labelFor(stage)} updated.`); setTimeout(() => setNotice(''), 2500) } catch (err) { setError(err.message) } finally { setBusy(false) } }; if (loading) return <Shell user={user} onSignOut={onSignOut}><div className="loading-screen">Loading your projectâ€¦</div></Shell>; if (!project) return <Shell user={user} onSignOut={onSignOut}><div className="empty-state">{error || 'Project not found.'}</div></Shell>; const doc = project.stages[active] || {}; return <Shell user={user} project={project} onSignOut={onSignOut}><main className="workspace"><WorkflowNav project={project} active={active} /><div className="workspace-heading"><div><p className="kicker">{doc.status?.toUpperCase()} Â· {stages.find((stage) => stage.key === active)?.agent}</p><h1>{labelFor(active)}</h1></div><span className="progress-label">{project.progress || 0}% complete</span></div>{notice && <div className="notice">âœ“ {notice}</div>}{error && <div className="error-banner">{error}</div>}<StageView project={project} stage={active} doc={doc} busy={busy} onAction={act} /></main></Shell> }
function WorkflowNav({ project, active }) { return <nav className="workflow-nav">{stages.map((stage, index) => { const doc = project.stages[stage.key] || {}; return <button key={stage.key} disabled={doc.status === 'locked'} className={`${active === stage.key ? 'selected' : ''} ${doc.status || ''}`} onClick={() => go(`/projects/${project.id}/${stage.path}`)}><span>{doc.status === 'approved' ? 'âœ“' : doc.status === 'locked' ? 'â—‹' : `0${index + 1}`}</span>{stage.label}</button> })}</nav> }
function StageView({ stage, doc, busy, onAction }) { if (!doc.data && ['available', 'outdated'].includes(doc.status)) return <GenerateState stage={stage} busy={busy} onAction={onAction} outdated={doc.status === 'outdated'} />; if (!doc.data) return <div className="stage-empty"><span className="empty-mark">â—‹</span><h2>This stage is locked.</h2><p>Approve the previous stage to open this part of the studio.</p></div>; if (stage === 'challenge') return <Challenge data={doc.data} busy={busy} onAction={onAction} />; if (stage === 'consistency') return <Consistency data={doc.data} busy={busy} onAction={onAction} />; return <Editable stage={stage} data={doc.data} status={doc.status} busy={busy} onAction={onAction} /> }
function GenerateState({ stage, busy, onAction, outdated }) { const meta = stages.find((item) => item.key === stage); return <div className="generate-state"><div className="agent-orbit">âœ¦</div><p className="kicker">{outdated ? 'UPSTREAM CHANGE DETECTED' : 'READY WHEN YOU ARE'}</p><h2>{outdated ? 'This direction needs a fresh look.' : `${meta.agent} is ready.`}</h2><p>{outdated ? 'A previous decision changed. Regenerate this stage to bring the system back into alignment.' : 'Generate a considered first direction from the decisions already approved.'}</p><button className="button button-accent" disabled={busy} onClick={() => onAction('generate')}>{busy ? 'Workingâ€¦' : 'Generate direction â†—'}</button></div> }
function Editable({ stage, data, status, busy, onAction }) { const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(JSON.stringify(data, null, 2)); const save = () => { try { onAction('edit', stage, JSON.parse(draft)); setEditing(false) } catch { } }; const cards = stage === 'discovery' ? [['Core idea', data.core_idea], ['Problem', data.problem], ['Context', data.context], ['Target audience', text(data.target_audience)], ['Audience needs', text(data.needs)], ['Constraints', text(data.constraints)], ['Assumptions', text(data.assumptions)], ['Open questions', text(data.open_questions)]] : stage === 'positioning' ? [['Category', data.category], ['Value proposition', data.value_proposition], ['Core benefit', data.core_benefit], ['Differentiator', data.differentiator], ['Positioning statement', data.positioning_statement], ['Rationale', data.rationale]] : stage === 'visualize' ? [['Visual concept', data.concept], ['Imagery direction', data.imagery], ['Composition', data.composition], ['Logo direction', data.logo_direction], ['Visual rules', text(data.visual_rules?.do)]] : [['Personality', text(data.personality?.traits)], ['Traits to avoid', text(data.personality?.avoid_traits)], ['Selected name', data.naming?.selected_name || 'No name selected'], ['Tagline', data.tagline], ['Voice', data.voice?.description], ['Tone', data.voice?.tone], ['Writing principles', text(data.voice?.writing_principles)]]; return <div className="stage-content"><div className="content-actions"><span className={`review-badge ${status}`}>{status === 'approved' ? 'âœ“ Approved' : status === 'outdated' ? 'Needs review' : 'In review'}</span><div><button className="button button-quiet" onClick={() => setEditing(!editing)}>{editing ? 'Cancel' : 'Edit'}</button><button className="button button-quiet" disabled={busy} onClick={() => onAction('regenerate', stage)}>Regenerate</button>{status !== 'approved' && <button className="button button-dark" disabled={busy} onClick={() => onAction('approve', stage)}>Approve & continue â†—</button>}</div></div>{editing ? <div className="editor"><p>Edit the structured stage data. NEXIRA will preserve it as a user-edited version.</p><textarea value={draft} onChange={(event) => setDraft(event.target.value)} rows="22" /><button className="button button-accent" onClick={save}>Save changes</button></div> : <><div className="insight-grid">{cards.map(([label, value]) => <article className="insight-card" key={label}><span>{label}</span><p>{value || 'Not yet defined'}</p></article>)}</div>{stage === 'positioning' && <Options title="Alternative directions" items={data.alternatives} />}{stage === 'shape' && <Options title="Naming territories" items={data.naming?.territories} />}{stage === 'visualize' && <Colors data={data} />}</>}</div> }
function Options({ title, items = [] }) { return <section className="detail-section"><h3>{title}</h3><div className="option-grid">{items?.length ? items.map((item, index) => <article key={index}><strong>{item.direction || item.name || item.territory || `Direction ${index + 1}`}</strong><p>{item.statement || item.rationale || item.concept}</p></article>) : <p className="muted">No additional directions were returned.</p>}</div></section> }
function Colors({ data }) { const color = data.color_direction || {}; return <section className="detail-section"><h3>Color system</h3><div className="swatches">{[color.primary, ...(color.secondary || []), ...(color.accent || [])].filter(Boolean).map((item, index) => <div key={index}><i style={{ background: item }} /><span>{item}</span></div>)}</div><p className="muted">{color.rationale}</p></section> }
function Challenge({ data, busy, onAction }) { return <div className="stage-content critic"><div className="critic-title"><p className="kicker">NEXIRA CRITIC</p><h2>Challenge the brand<br /><em>before you launch it.</em></h2><p>{data.overall_summary}</p></div><div className="critic-columns"><section><h3>Potential issues <span>{data.issues?.length || 0}</span></h3>{(data.issues || []).map((issue, index) => <article className="issue-card" key={index}><div><strong>{issue.category}</strong><span className="severity">{issue.severity}</span></div><p>{issue.issue}</p><small>{issue.evidence}</small><footer>{issue.suggested_action}</footer></article>)}</section><section><h3>Strengths</h3>{(data.strengths || []).map((item, index) => <p className="strength" key={index}>âœ“ {item}</p>)}</section></div><div className="content-actions bottom-actions"><button className="button button-quiet" disabled={busy} onClick={() => onAction('regenerate')}>Run critique again</button></div></div> }
function Consistency({ data, busy, onAction }) { return <div className="stage-content"><div className="consistency-hero"><div><p className="kicker">AI CONSISTENCY ASSESSMENT</p><h2>{Math.round((data.score || 0) * 100)}<small>/100</small></h2><p>This is an AI assessment of how well the current components relate. It is a signal for review, not an objective quality score.</p></div><div className="relationship-map"><span>POSITIONING</span><b>BRAND</b><span>NAME Â· VISUAL Â· VOICE</span><span>AUDIENCE</span></div></div><div className="check-list">{(data.checks || []).map((check, index) => <article key={index}><span className={check.status === 'pass' || check.status === 'consistent' ? 'pass' : 'warn'}>{check.status === 'pass' || check.status === 'consistent' ? 'âœ“' : '!'}</span><div><strong>{check.relationship}</strong><p>{check.explanation}</p></div><small>{check.recommendation}</small></article>)}</div><div className="content-actions bottom-actions"><button className="button button-quiet" disabled={busy} onClick={() => onAction('regenerate')}>Run assessment again</button><button className="button button-dark" disabled={busy} onClick={() => onAction('approve')}>Approve & deliver â†—</button></div></div> }
function Admin({ user, onSignOut }) { const [users, setUsers] = useState([]); const [error, setError] = useState(''); useEffect(() => { if (user?.role === 'admin') api.admin.list().then(setUsers).catch((err) => setError(err.message)) }, [user]); if (user?.role !== 'admin') return <Shell user={user} onSignOut={onSignOut}><div className="empty-state"><h2>Access restricted.</h2><p>Admin access is required for this workspace.</p></div></Shell>; return <Shell user={user} onSignOut={onSignOut}><main className="dashboard"><div className="page-heading"><div><p className="kicker">OPERATIONS</p><h1>Admin<br /><em>dashboard.</em></h1></div></div>{error && <p className="form-error">{error}</p>}<div className="admin-table"><div className="table-head"><span>User</span><span>Email</span><span>Role</span><span>Created</span><span /></div>{users.map((item) => <div className="table-row" key={item.id}><strong>{item.first_name} {item.last_name}</strong><span>{item.email}</span><span className="role-label">{item.role}</span><span>{prettyDate(item.created_at)}</span><button className="text-button" onClick={async () => { try { const updated = await api.admin.setRole(item.id, item.role === 'admin' ? 'user' : 'admin'); setUsers(users.map((candidate) => candidate.id === updated.id ? updated : candidate)) } catch (err) { setError(err.message) } }}>{item.role === 'admin' ? 'Demote' : 'Promote'}</button></div>)}</div></main></Shell> }

export default App
